SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SalvarCliente
	@CPF VARCHAR(10),
	@Nome VARCHAR(255),
	@RG VARCHAR(10),
	@DATAEXPEDCAO DATETIME,
	@ORGAOEXPEDICAO VARCHAR(255),
	@UF VARCHAR(2),
	@DATANASCIMENTO DATETIME,
	@SEXO VARCHAR(15),
	@ESTADOCIVIL VARCHAR(15),
	@LOGIN VARCHAR(20),
	@SENHA VARCHAR(20),
	@NewId INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Clientes (CPF,Nome,RG,DataExpedicao,OrgaoExpedicao,UF,DataNascimento,Sexo,EstadoCivil,Login,Senha) VALUES (@CPF,@Nome,@RG,@DATAEXPEDCAO,@ORGAOEXPEDICAO,@UF,@DATANASCIMENTO,@SEXO,@ESTADOCIVIL,@LOGIN,@SENHA);
	SET @NewId= SCOPE_IDENTITY()
	
	RETURN @NewId;
END
GO
