SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SalvarEndereco
	@IDCLIENTE INT,
	@CEP VARCHAR(10),
	@LOGRADOURO VARCHAR(255),
	@NUMERO VARCHAR(10),
	@COMPLEMENTO VARCHAR(255),
	@BAIRRO VARCHAR(50),
	@CIDADE VARCHAR(50),
	@UF VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Enderecos (IdCliente,CEP,Logradouro,Numero,Complemento,Bairro,Cidade,UF) VALUES (@IDCLIENTE,@Nome,@CEP,@LOGRADOURO,@NUMERO,@COMPLEMENTO,@BAIRRO,@CIDADE,@UF);

END
GO
